baseURL = 'https://opensourcemetrics.org/'
languageCode = 'en-us'
title = 'Open Source Business Metrics'
theme = 'terminal'
copyright = 'Copyright Â© 2023 Open Source Business Metrics Maintainers'

[languages.en.params.logo]
  logoText = "Open Source Business Metrics"
  logoHomeLink = "/"

[params]
  themeColor = "blue"
  centerTheme = true
  fullWidthTheme = false
  showLastUpdated = true
  cover =  "/images/OSS Metrics-Guidebook.png"

[[languages.en.menu.main]]
  identifier = "guide"
  name = "Read the Guide"
  url = "/posts/open-source-business-metrics-guide/"
  
[[languages.en.menu.main]]
  identifier = "metrics"
  name = "Explore Metrics"
  url = "/metrics/"
 
[[languages.en.menu.main]]
  identifier = "resources"
  name = "External Resources"
  url = "/resources/external/" 
  
[[languages.en.menu.main]]
 identifier = "podcasts"
 name = "Podcasts"
 url = "/podcasts/" 

[[languages.en.menu.main]]
 identifier = "github"
 name = "GitHub"
 url = "https://github.com/scarf-sh/oss-metrics" 

[[languages.en.menu.main]]
 identifier = "discord"
 name = "Discord"
 url = "https://discord.gg/7HvFURHxAM" 